server:
  port:8080

#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: user
#          uri: lb://USER
#          predicates:
#            - Path=/users/**
#        - id: dataquadrequirementsapi
#          uri: lb://DATAQUADREQUIREMENTSAPI
#          predicates:
#            - Path=/requirements/**
#        - id: candidate
#          uri: lb://CANDIDATES
#          predicates:
#            - Path=/candidate/**


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: requirements_service
          uri: lb://requirements-service
          predicates:
            - Path=/requirements/**
        - id: candidates_service
          uri: lb://candidates-service
          predicates:
            - Path=/candidate/**


#eureka:
#  client:
#    service-url:
#      defaultZone: http://eurekaserver1:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
#    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.web: DEBUG